insert into teams (id, group_code, access_code_hash, variant, current_stage, created_at) values
('A1', 'G-A-1', 'mock-hash-A1', 'A', 1, now()),
('A2', 'G-A-2', 'mock-hash-A2', 'A', 1, now()),
('A3', 'G-A-3', 'mock-hash-A3', 'A', 1, now()),
('A4', 'G-A-4', 'mock-hash-A4', 'A', 1, now()),
('A5', 'G-A-5', 'mock-hash-A5', 'A', 1, now()),
('A6', 'G-A-6', 'mock-hash-A6', 'A', 1, now()),
('A7', 'G-A-7', 'mock-hash-A7', 'A', 1, now()),
('B1', 'G-B-1', 'mock-hash-B1', 'B', 1, now()),
('B2', 'G-B-2', 'mock-hash-B2', 'B', 1, now()),
('B3', 'G-B-3', 'mock-hash-B3', 'B', 1, now()),
('B4', 'G-B-4', 'mock-hash-B4', 'B', 1, now()),
('B5', 'G-B-5', 'mock-hash-B5', 'B', 1, now()),
('B6', 'G-B-6', 'mock-hash-B6', 'B', 1, now()),
('B7', 'G-B-7', 'mock-hash-B7', 'B', 1, now()),
('C1', 'G-C-1', 'mock-hash-C1', 'C', 1, now()),
('C2', 'G-C-2', 'mock-hash-C2', 'C', 1, now()),
('C3', 'G-C-3', 'mock-hash-C3', 'C', 1, now()),
('C4', 'G-C-4', 'mock-hash-C4', 'C', 1, now()),
('C5', 'G-C-5', 'mock-hash-C5', 'C', 1, now()),
('C6', 'G-C-6', 'mock-hash-C6', 'C', 1, now()),
('C7', 'G-C-7', 'mock-hash-C7', 'C', 1, now()),
('D1', 'G-D-1', 'mock-hash-D1', 'D', 1, now()),
('D2', 'G-D-2', 'mock-hash-D2', 'D', 1, now()),
('D3', 'G-D-3', 'mock-hash-D3', 'D', 1, now()),
('D4', 'G-D-4', 'mock-hash-D4', 'D', 1, now()),
('D5', 'G-D-5', 'mock-hash-D5', 'D', 1, now()),
('D6', 'G-D-6', 'mock-hash-D6', 'D', 1, now()),
('D7', 'G-D-7', 'mock-hash-D7', 'D', 1, now());

insert into stages (stage_number, title, case_development, status, released_at, closed_at) values
(1, 'Initial Underwriting', 'Project mobilisation begins with AP bond controls.', 'closed', now(), now()),
(2, 'Contract Amendment', 'Month 16: contract value increases and margins compress.', 'closed', now(), now()),
(3, 'Red Flags and Deterioration', 'Month 31: progress and documentation issues emerge.', 'closed', now(), now()),
(4, 'Termination and Pre-Claim Preparation', 'Month 43: termination and exposure build sharply.', 'open', now(), null),
(5, 'Claim and Recovery', 'Final bond claims and coordinated recovery strategy are released.', 'locked', null, null);
